#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 29 13:39:52 2020

@author: romankosarzycki
"""

import numpy as np

def GaussInteg(func,N,q0):
    QDERIV=np.zeros((N,1))
    for i in range(0,N):
        x=-1+i*(2/N)
        qderiv=2*q0/(-1+x)**2
        QDERIV[i-1]=qderiv
    sum=0
    return QDERIV
        
print(GaussInteg(1,20,1))
